adding security scan to ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,7 @@ jobs:
         run: yarn lint
 
   # 3) Tests unitaires / composants (couverture)
-  unit-component-tests:
+  cypress-tests:
     runs-on: ubuntu-latest
     needs: deps
 
@@ -83,3 +83,27 @@ jobs:
     
       - name: Run Cypress tests with coverage
         run: yarn cypress:run --env coverage=true
+
+  security-scan:
+      runs-on: ubuntu-latest
+      needs: deps
+
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+
+        - name: Use Node.js 20
+          uses: actions/setup-node@v4
+          with:
+            node-version: 20
+            cache: yarn
+
+        - name: Enable Corepack
+          run: corepack enable || true
+
+        - name: Install dependencies
+          run: yarn install
+
+        # Remove "|| true" if you want the pipeline to fail on high vulns
+        - name: Security scan (high/critical vulns)
+          run: yarn audit --level high || true
